[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'mkdir -p storage/framework/sessions',
    'mkdir -p storage/framework/views',
    'mkdir -p storage/framework/cache',
    'mkdir -p storage/logs',
    'mkdir -p database',
    'touch database/database.sqlite',
    'chmod -R 775 storage',
    'chmod -R 775 bootstrap/cache',
    'php artisan migrate --force'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'